import type { Exercise } from './types';

/**
 * The catalogue. Every entry is written for one player: 52 years old, pickleball
 * three times a week, Achilles tendinopathy with morning stiffness, occasional
 * adductor and deep-glute strains, an old right shoulder, training at home with
 * 5 kg dumbbells, bands, a loadable backpack, a patio and a roof terrace.
 */
const list: Exercise[] = [
  /* ── Tobillo y Aquiles ──────────────────────────────────────────────── */
  {
    key: 'iso-calf-double',
    name: 'Isométrico de gemelo (dos piernas)',
    tagline: 'Calma el tendón y lo prepara para cargar',
    anim: 'iso-calf-double',
    equipment: ['ninguno', 'pared'],
    targets: ['Gemelo', 'Tendón de Aquiles'],
    why: 'Los isométricos largos bajan el dolor del tendón durante varias horas. Es el ejercicio con el que arrancas cuando el Aquiles está irritable, y el que harás antes de jugar.',
    setup: ['De pie, pies a la anchura de la cadera', 'Apoya los dedos en una pared si lo necesitas'],
    execution: [
      'Sube a puntillas lo más alto que puedas',
      'Aguanta ahí 45 segundos apretando el gemelo',
      'Baja despacio, en 3 segundos',
    ],
    mistakes: ['Subir solo a medias', 'Aguantar conteniendo la respiración', 'Dejarse caer al bajar'],
    painRule: 'Durante el isométrico no debería doler más de 3/10. Si duele más, hazlo sentado.',
    levels: [
      { n: 1, name: 'Dos piernas, sin peso' },
      { n: 2, name: 'Dos piernas con mochila ligera' },
      { n: 3, name: 'A una pierna', anim: 'iso-calf-single' },
    ],
    unilateral: false,
  },
  {
    key: 'iso-calf-single',
    name: 'Isométrico de gemelo a una pierna',
    tagline: 'La versión que de verdad carga el tendón',
    anim: 'iso-calf-single',
    equipment: ['pared'],
    targets: ['Gemelo', 'Tendón de Aquiles'],
    why: 'A una pierna cargas tu peso entero sobre un solo tendón, que es lo que pasa en cada paso lateral en la pista.',
    setup: ['Dedos apoyados en la pared solo para equilibrio', 'Rodilla estirada'],
    execution: ['Sube a puntillas con una pierna', 'Aguanta arriba sin balancearte', 'Baja en 3 s y cambia'],
    mistakes: ['Cargar el peso en la mano de la pared', 'Torcer el tobillo hacia fuera'],
    painRule: 'Hasta 5/10 durante. Lo importante es cómo amanezcas mañana.',
    levels: [
      { n: 1, name: 'Con los dedos bien apoyados en la pared' },
      { n: 2, name: 'Apoyo mínimo, solo para el equilibrio' },
      { n: 3, name: 'Con mochila cargada' },
    ],
    unilateral: true,
  },
  {
    key: 'calf-raise-floor',
    name: 'Elevación de talones en el suelo',
    tagline: 'Carga pesada y lenta, en rango seguro',
    anim: 'calf-raise-floor',
    equipment: ['ninguno'],
    targets: ['Gemelo', 'Tendón de Aquiles'],
    why: 'En el suelo (sin bajar del escalón) el tendón no se comprime contra el hueso del talón. Es el punto de partida correcto cuando hay rigidez por las mañanas.',
    setup: ['Pies a la anchura de la cadera, dedos al frente', 'Peso repartido en los dos pies'],
    execution: ['Sube en 2 s hasta el tope', 'Aprieta 1 s arriba', 'Baja en 3 s hasta que el talón toque el suelo'],
    mistakes: ['Ir rápido: el tempo lento es el ejercicio', 'Dejar caer el talón de golpe'],
    painRule: 'Hasta 5/10. Si mañana amaneces peor que hoy, bajas una serie.',
    levels: [
      { n: 1, name: 'Dos piernas, sin peso' },
      { n: 2, name: 'Dos piernas con mochila' },
      { n: 3, name: 'A una pierna', anim: 'calf-raise-single' },
    ],
    unilateral: false,
  },
  {
    key: 'calf-raise-single',
    name: 'Elevación de talón a una pierna',
    tagline: 'El ejercicio central de todo el programa',
    anim: 'calf-raise-single',
    equipment: ['pared', 'mochila'],
    targets: ['Gemelo', 'Tendón de Aquiles'],
    why: 'Es el que más cambia las cosas: un tendón fuerte tolera los frenazos y arrancadas del pickleball. Con la mochila cargada tienes estímulo de sobra sin pisar un gimnasio.',
    setup: ['Dedos en la pared para equilibrio', 'Mochila cargada a la espalda', 'Rodilla estirada'],
    execution: ['Sube en 2 s hasta el tope del recorrido', 'Baja en 3 s controlando', 'Completa todas las repes antes de cambiar'],
    mistakes: ['Rebotar abajo', 'Doblar la rodilla (eso ya es sóleo)', 'Rango corto arriba'],
    painRule: 'Hasta 5/10 durante. La rigidez de mañana no debe ser peor que la de hoy.',
    levels: [
      { n: 1, name: 'Sin peso' },
      { n: 2, name: 'Mochila de 8 a 12 kg' },
      { n: 3, name: 'Mochila de 15 a 20 kg' },
    ],
    unilateral: true,
  },
  {
    key: 'heel-drop-step',
    name: 'Bajada de talón desde escalón',
    tagline: 'Rango completo, solo cuando el tendón lo permita',
    anim: 'heel-drop-step',
    equipment: ['escalon', 'pared'],
    targets: ['Tendón de Aquiles', 'Gemelo'],
    why: 'Añade el rango final de estiramiento del tendón. Se introduce en la fase 2 y solo si la rigidez matutina ya está en 2/10 o menos, porque en un tendón irritable este rango puede empeorarlo.',
    setup: ['Antepié en el borde del escalón, talón al aire', 'Una mano en la pared'],
    execution: ['Baja el talón en 3 s por debajo del escalón', 'Sube con las dos piernas', 'Baja otra vez con una'],
    mistakes: ['Empezar por aquí en la fase 1', 'Bajar de golpe', 'Hacerlo si notas pinchazo justo en el hueso del talón'],
    painRule: 'Si te duele exactamente donde el tendón se pega al hueso, salta este ejercicio y quédate en el suelo.',
    levels: [
      { n: 1, name: 'Sube y baja con las dos piernas' },
      { n: 2, name: 'Sube con dos, baja con una' },
      { n: 3, name: 'Baja con una y con mochila' },
    ],
    unilateral: true,
  },
  {
    key: 'soleus-seated',
    name: 'Sóleo sentado con peso',
    tagline: 'El músculo olvidado que aguanta tus frenadas',
    anim: 'soleus-seated',
    equipment: ['silla', 'mancuernas'],
    targets: ['Sóleo', 'Tendón de Aquiles'],
    why: 'Con la rodilla doblada el gemelo se apaga y trabaja el sóleo, que es el que absorbe la carga en cada frenada. Casi nadie lo entrena y en tu caso es clave. Además aquí tus mancuernas de 5 kg sí son suficientes.',
    setup: ['Sentado, rodillas a 90°', 'Una mancuerna sobre cada muslo, cerca de la rodilla'],
    execution: ['Sube los talones todo lo que puedas en 2 s', 'Aprieta 1 s', 'Baja en 3 s'],
    mistakes: ['Poner el peso sobre la rodilla en vez del muslo', 'Recorrido corto'],
    levels: [
      { n: 1, name: 'Sin peso' },
      { n: 2, name: 'Una mancuerna sobre cada muslo' },
      { n: 3, name: 'A una pierna con 5 kg' },
    ],
    unilateral: false,
  },
  {
    key: 'soleus-wall-iso',
    name: 'Isométrico de sóleo en la pared',
    tagline: 'Sentadilla en pared, pero de puntillas',
    anim: 'soleus-wall-iso',
    equipment: ['pared'],
    targets: ['Sóleo'],
    why: 'Añade resistencia al sóleo sin necesidad de carga externa. Muy útil el día antes de jugar, porque cansa poco y prepara el tobillo.',
    setup: ['Espalda en la pared, rodillas a unos 60°', 'Pies bajo las rodillas'],
    execution: ['Sube los talones y aguanta', 'Mantén las rodillas dobladas todo el tiempo', 'Respira normal'],
    mistakes: ['Estirar las rodillas (entonces ya no es sóleo)'],
    levels: [
      { n: 1, name: 'Rodillas a 45°' },
      { n: 2, name: 'Rodillas a 60°' },
      { n: 3, name: 'Rodillas a 60° con mochila' },
    ],
    unilateral: false,
  },
  {
    key: 'knee-to-wall',
    name: 'Movilidad de tobillo rodilla-pared',
    tagline: 'Gana centímetros de tobillo, quita carga al Aquiles',
    anim: 'knee-to-wall',
    equipment: ['pared'],
    targets: ['Tobillo', 'Tibial anterior'],
    why: 'Un tobillo rígido obliga al Aquiles a trabajar de más y te roba potencia en la flexión de rodilla. Es movilidad activa, no un estiramiento pasivo: se puede hacer incluso antes de jugar.',
    setup: ['Pie a un palmo de la pared', 'Talón pegado al suelo todo el rato'],
    execution: ['Lleva la rodilla hacia la pared sin levantar el talón', 'Toca y vuelve', 'Si tocas fácil, aleja el pie un dedo más'],
    mistakes: ['Levantar el talón', 'Dejar caer el arco del pie hacia dentro'],
    levels: [
      { n: 1, name: 'Buscando llegar a la pared' },
      { n: 2, name: 'El pie un dedo más atrás' },
      { n: 3, name: 'Con pausa de 2 s en el tope' },
    ],
    unilateral: true,
  },
  {
    key: 'toe-walk',
    name: 'Marcha de puntillas',
    tagline: 'Resistencia del gemelo, fácil de meter en el patio',
    anim: 'toe-walk',
    equipment: ['ninguno'],
    targets: ['Gemelo', 'Sóleo'],
    why: 'Trabaja la resistencia del tendón, que es lo que falla en el tercer set. Lo haces caminando por el patio, sin material.',
    setup: ['Espacio para 10-15 pasos'],
    execution: ['Camina de puntillas sin dejar caer el talón en ningún momento', 'Pasos cortos', 'Da la vuelta y sigue'],
    mistakes: ['Bajar el talón entre pasos', 'Ir demasiado rápido'],
    levels: [
      { n: 1, name: 'Pasos cortos' },
      { n: 2, name: 'Recorrido más largo' },
      { n: 3, name: 'Con mochila cargada' },
    ],
    unilateral: false,
  },

  /* ── Aductores e ingle ──────────────────────────────────────────────── */
  {
    key: 'adductor-squeeze',
    name: 'Isométrico de aductores con cojín',
    tagline: 'El test y el remedio de tus tirones de ingle',
    anim: 'adductor-squeeze',
    equipment: ['cojin'],
    targets: ['Aductores'],
    why: 'La fuerza de aductores medida con este apretón predice las lesiones de ingle. Es tu semáforo: si un día notas que aprietas con menos fuerza o molesta, ese día no toca trabajo lateral fuerte.',
    setup: ['Tumbado o sentado, rodillas dobladas', 'Cojín o pelota entre las rodillas'],
    execution: ['Aprieta progresivamente hasta el 80 % de tu fuerza', 'Aguanta 30 s', 'Suelta despacio'],
    mistakes: ['Apretar de golpe al máximo', 'Apretar también los glúteos'],
    painRule: 'Si al apretar notas pinchazo en la ingle, para y avísalo en el registro.',
    levels: [
      { n: 1, name: 'Rodillas dobladas' },
      { n: 2, name: 'Piernas estiradas' },
      { n: 3, name: 'Piernas estiradas, apretón largo' },
    ],
    unilateral: false,
  },
  {
    key: 'copenhagen-short',
    name: 'Copenhagen palanca corta',
    tagline: 'El mejor ejercicio que existe para la ingle',
    anim: 'copenhagen-short',
    equipment: ['silla', 'esterilla'],
    targets: ['Aductores', 'Oblicuos'],
    why: 'En los estudios con futbolistas reduce las lesiones de ingle casi a la mitad. Empiezas por la versión corta, apoyando la rodilla, porque la larga es muy dura de entrada.',
    setup: [
      'Tumbado de lado, antebrazo de abajo en el suelo',
      'Rodilla de la pierna de arriba apoyada en la silla',
      'La pierna de abajo, relajada',
    ],
    execution: ['Sube la cadera hasta formar una línea recta', 'Aguanta 2 s arriba', 'Baja controlando sin apoyar del todo'],
    mistakes: ['Rotar el tronco hacia el suelo', 'Dejar caer la cadera', 'Hacer muchas repes el primer día'],
    painRule: 'Es normal notar tensión en la ingle. Pinchazo agudo, no: para.',
    levels: [
      { n: 1, name: 'Rodilla en la silla, recorrido corto' },
      { n: 2, name: 'Rodilla en la silla, hasta la línea recta' },
      { n: 3, name: 'Con pausa de 2 s arriba' },
    ],
    unilateral: true,
  },
  {
    key: 'copenhagen-long',
    name: 'Copenhagen palanca larga',
    tagline: 'La versión completa, en la fase 2',
    anim: 'copenhagen-long',
    equipment: ['silla', 'esterilla'],
    targets: ['Aductores', 'Oblicuos'],
    why: 'Con la pierna estirada el brazo de palanca es mucho mayor y la exigencia sobre el aductor se dispara. Aquí es donde se construye de verdad la ingle a prueba de tirones.',
    setup: ['Como la versión corta, pero apoyando el tobillo en la silla', 'Pierna de arriba estirada'],
    execution: ['Sube la cadera hasta la línea recta', 'Aguanta 2 s', 'Baja en 3 s'],
    mistakes: ['Pasar a esta versión antes de dominar la corta con 3 x 10'],
    painRule: 'Si al día siguiente tienes agujetas fuertes en la ingle, baja una serie la próxima vez.',
    levels: [
      { n: 1, name: 'Tobillo en la silla, recorrido corto' },
      { n: 2, name: 'Tobillo en la silla, hasta la línea recta' },
      { n: 3, name: 'Con pausa de 2 s arriba' },
    ],
    unilateral: true,
  },
  {
    key: 'side-lying-adduction',
    name: 'Aducción tumbado de lado',
    tagline: 'Entrada suave al trabajo de aductor',
    anim: 'side-lying-adduction',
    equipment: ['esterilla'],
    targets: ['Aductores'],
    why: 'Es la versión amable del Copenhagen: mismo músculo, mucha menos carga. Perfecta para las semanas 1-2 y para los días en que la ingle esté sensible.',
    setup: ['Tumbado de lado, pierna de arriba cruzada por delante', 'Pierna de abajo estirada'],
    execution: ['Sube la pierna de abajo todo lo que puedas', 'Aguanta 2 s', 'Baja sin apoyar'],
    mistakes: ['Rotar la cadera hacia atrás', 'Impulsarse con el tronco'],
    levels: [
      { n: 1, name: 'Sin peso' },
      { n: 2, name: 'Con pausa de 2 s arriba' },
      { n: 3, name: 'Con banda o tobillera lastrada' },
    ],
    unilateral: true,
  },
  {
    key: 'lateral-lunge',
    name: 'Zancada lateral',
    tagline: 'El gesto exacto del pickleball, con carga',
    anim: 'lateral-lunge',
    equipment: ['ninguno', 'mancuernas'],
    targets: ['Aductores', 'Glúteo medio', 'Cuádriceps'],
    why: 'Reproduce el desplazamiento lateral con el que te dan los tirones, pero controlado y con carga progresiva. Entrenar el gesto en el que te lesionas es lo que hace que deje de lesionarte.',
    setup: ['De pie, pies juntos', 'Manos al pecho o mancuernas colgando'],
    execution: ['Da un paso amplio al lado', 'Cadera atrás, pecho alto, la otra pierna estirada', 'Empuja fuerte para volver al centro'],
    mistakes: ['Dejar que la rodilla se meta hacia dentro', 'Paso demasiado corto'],
    levels: [
      { n: 1, name: 'Sin peso, paso corto' },
      { n: 2, name: 'Con mancuernas' },
      { n: 3, name: 'Con mochila y paso amplio' },
    ],
    unilateral: true,
  },
  {
    key: 'cossack-squat',
    name: 'Sentadilla cosaco',
    tagline: 'Fuerza de aductor en rango largo',
    anim: 'cossack-squat',
    equipment: ['ninguno'],
    targets: ['Aductores', 'Glúteo medio', 'Cadera'],
    why: 'Fortalece el aductor en la posición estirada, que es justo donde se rompe cuando llegas forzado a una bola ancha. Hazlo despacio, no es un ejercicio de rango a la fuerza.',
    setup: ['Pies muy abiertos, puntas ligeramente hacia fuera'],
    execution: ['Baja hacia un lado doblando esa rodilla', 'La otra pierna estirada, punta arriba', 'Sube empujando con el talón'],
    mistakes: ['Forzar la profundidad el primer día', 'Levantar el talón del pie que baja'],
    levels: [
      { n: 1, name: 'Rango corto, con apoyo' },
      { n: 2, name: 'Rango completo sin apoyo' },
      { n: 3, name: 'Con 5 kg al pecho' },
    ],
    unilateral: true,
  },

  /* ── Cadera, glúteo y piramidal ─────────────────────────────────────── */
  {
    key: 'glute-bridge',
    name: 'Puente de glúteos',
    tagline: 'Enciende el glúteo para que el piramidal descanse',
    anim: 'glute-bridge',
    equipment: ['esterilla'],
    targets: ['Glúteo mayor', 'Isquiotibiales'],
    why: 'Cuando el glúteo mayor no tira, el piramidal hace su trabajo y se sobrecarga. De ahí tus molestias. Este es el ejercicio base para repartir esa carga.',
    setup: ['Tumbado boca arriba, rodillas dobladas', 'Talones a un palmo del glúteo'],
    execution: ['Empuja con los talones y sube la cadera', 'Aprieta el glúteo 2 s arriba', 'Baja sin llegar a apoyar del todo'],
    mistakes: ['Arquear la lumbar en vez de extender la cadera', 'Subir empujando con las puntas'],
    levels: [
      { n: 1, name: 'Dos piernas' },
      { n: 2, name: 'Dos piernas con mochila en la cadera' },
      { n: 3, name: 'A una pierna', anim: 'single-leg-bridge' },
    ],
    unilateral: false,
  },
  {
    key: 'single-leg-bridge',
    name: 'Puente a una pierna',
    tagline: 'Glúteo e isquios, sin equipo',
    anim: 'single-leg-bridge',
    equipment: ['esterilla'],
    targets: ['Glúteo mayor', 'Isquiotibiales'],
    why: 'A una pierna la exigencia se dobla y además destapa asimetrías entre un lado y otro, que suelen estar detrás de las molestias que van solo a un lado.',
    setup: ['Como el puente, pero con una pierna en el aire'],
    execution: ['Sube la cadera empujando con un solo talón', 'Mantén la pelvis nivelada', 'Baja controlando'],
    mistakes: ['Que caiga la cadera del lado libre', 'Empujar con la espalda'],
    levels: [
      { n: 1, name: 'Pies en el suelo' },
      { n: 2, name: 'Con pausa de 2 s arriba' },
      { n: 3, name: 'Pies elevados en una silla' },
    ],
    unilateral: true,
  },
  {
    key: 'clamshell-band',
    name: 'Almeja con banda',
    tagline: 'Glúteo medio y rotadores, directo al piramidal',
    anim: 'clamshell-band',
    equipment: ['banda', 'esterilla'],
    targets: ['Glúteo medio', 'Rotadores de cadera'],
    why: 'Los rotadores profundos de la cadera, el piramidal incluido, se quejan cuando son débiles y les toca estabilizar cada apoyo. Fortalecerlos es mejor solución que estirarlos.',
    setup: ['Tumbado de lado, rodillas dobladas 90°', 'Banda por encima de las rodillas'],
    execution: ['Abre la rodilla de arriba sin girar la pelvis', 'Aguanta 2 s', 'Cierra despacio'],
    mistakes: ['Girar la cadera hacia atrás para abrir más', 'Ir rápido'],
    levels: [
      { n: 1, name: 'Sin banda' },
      { n: 2, name: 'Con banda suave' },
      { n: 3, name: 'Con banda dura' },
    ],
    unilateral: true,
  },
  {
    key: 'side-plank-abduction',
    name: 'Plancha lateral con abducción',
    tagline: 'Lateral del cuerpo entero en un solo ejercicio',
    anim: 'side-plank-abduction',
    equipment: ['esterilla'],
    targets: ['Glúteo medio', 'Oblicuos'],
    why: 'Un glúteo medio fuerte evita que la rodilla se te meta hacia dentro en los apoyos laterales, que es de donde salen tanto las molestias de cadera como buena parte de la carga extra al Aquiles.',
    setup: ['Plancha lateral sobre el antebrazo', 'Cuerpo en línea recta'],
    execution: ['Sube la pierna de arriba sin perder la línea', 'Aguanta 2 s', 'Baja despacio'],
    mistakes: ['Dejar caer la cadera', 'Llevar la pierna hacia delante'],
    levels: [
      { n: 1, name: 'Rodillas apoyadas' },
      { n: 2, name: 'Piernas estiradas' },
      { n: 3, name: 'Con banda en los muslos' },
    ],
    unilateral: true,
  },
  {
    key: 'banded-lateral-walk',
    name: 'Paso lateral con banda',
    tagline: 'Activación de glúteo medio en 60 segundos',
    anim: 'banded-lateral-walk',
    equipment: ['banda'],
    targets: ['Glúteo medio'],
    why: 'Es el activador más rápido que hay para el glúteo medio, por eso está en el calentamiento pre-partido: llegas a la pista con la cadera despierta.',
    setup: ['Banda en los tobillos o por encima de las rodillas', 'Medio sentado, pecho alto'],
    execution: ['Da pasos laterales manteniendo la tensión', 'No juntes nunca del todo los pies', 'Ida y vuelta'],
    mistakes: ['Ponerse de pie del todo', 'Balancear el tronco'],
    levels: [
      { n: 1, name: 'Banda por encima de las rodillas' },
      { n: 2, name: 'Banda en los tobillos' },
      { n: 3, name: 'Banda dura en los tobillos' },
    ],
    unilateral: false,
  },
  {
    key: 'hip-airplane',
    name: 'Hip airplane',
    tagline: 'Control rotacional de cadera, lo que más te falta',
    anim: 'hip-airplane',
    equipment: ['pared'],
    targets: ['Glúteo medio', 'Rotadores de cadera'],
    why: 'Enseña a la cadera a controlar la rotación sobre una sola pierna. Es exactamente lo que pides cada vez que giras para llegar a una bola, y donde el piramidal se queja si nadie más hace el trabajo.',
    setup: ['De pie sobre una pierna, tronco inclinado', 'La otra pierna estirada atrás', 'Apóyate en la pared al principio'],
    execution: ['Abre la cadera de arriba despacio', 'Vuelve a cerrar con control', 'Sin perder la línea tronco-pierna'],
    mistakes: ['Ir rápido: es un ejercicio de control, no de repes', 'Doblar la pierna de atrás'],
    levels: [
      { n: 1, name: 'Con las manos en la pared' },
      { n: 2, name: 'Sin apoyo' },
      { n: 3, name: 'Sin apoyo y con pausa de 3 s' },
    ],
    unilateral: true,
  },
  {
    key: 'hip-90-90',
    name: 'Rotaciones de cadera 90/90',
    tagline: 'Movilidad de rotación, sin estirar a lo bruto',
    anim: 'hip-90-90',
    equipment: ['esterilla'],
    targets: ['Rotadores de cadera', 'Piramidal'],
    why: 'Gana rotación de cadera moviéndote, no tirando. En tu caso es mejor que el estiramiento clásico de piramidal, porque las molestias de esa zona empeoran con el estiramiento agresivo.',
    setup: ['Sentado, una pierna delante a 90° y la otra al lado a 90°'],
    execution: ['Gira las dos rodillas al otro lado controlando', 'Pecho alto', 'Alterna sin prisa'],
    mistakes: ['Ayudarse con las manos tirando', 'Redondear mucho la espalda'],
    levels: [
      { n: 1, name: 'Ayudándote con las manos' },
      { n: 2, name: 'Sin manos' },
      { n: 3, name: 'Sin manos, levantándote al final' },
    ],
    unilateral: false,
  },
  {
    key: 'figure-4-stretch',
    name: 'Estiramiento figura 4',
    tagline: 'Descarga suave del glúteo profundo',
    anim: 'figure-4-stretch',
    equipment: ['esterilla'],
    targets: ['Piramidal', 'Glúteo'],
    why: 'Va en la vuelta a la calma, no antes de jugar. Suave: si tiras fuerte de un piramidal irritado, lo empeoras.',
    setup: ['Boca arriba, tobillo sobre la rodilla contraria'],
    execution: ['Tira suave del muslo de atrás', 'Aguanta 30 s respirando', 'Suelta y cambia'],
    mistakes: ['Tirar hasta el dolor', 'Contener la respiración'],
    painRule: 'Debe notarse tirantez cómoda, nunca dolor ni hormigueo por la pierna.',
    levels: [
      { n: 1, name: 'Tumbado, tirón suave' },
      { n: 2, name: 'Tumbado, aguante más largo' },
      { n: 3, name: 'Sentado, algo más de intensidad' },
    ],
    unilateral: true,
  },
  {
    key: 'single-leg-rdl',
    name: 'Peso muerto rumano a una pierna',
    tagline: 'Isquios, glúteo y equilibrio de una tacada',
    anim: 'single-leg-rdl',
    equipment: ['mancuernas'],
    targets: ['Isquiotibiales', 'Glúteo mayor'],
    why: 'Cadena posterior fuerte y equilibrio sobre una pierna: los dos ingredientes que te faltan para llegar a las bolas bajas sin que lo pague el Aquiles.',
    setup: ['De pie sobre una pierna, mancuerna en la mano contraria'],
    execution: ['Bisagra de cadera llevando la pierna libre atrás', 'Espalda recta, cadera nivelada', 'Sube apretando el glúteo'],
    mistakes: ['Redondear la espalda', 'Abrir la cadera hacia fuera', 'Doblar mucho la rodilla de apoyo'],
    levels: [
      { n: 1, name: 'Sin peso, rozando la pared' },
      { n: 2, name: 'Con una mancuerna' },
      { n: 3, name: 'Con dos mancuernas' },
    ],
    unilateral: true,
  },

  /* ── Pierna ─────────────────────────────────────────────────────────── */
  {
    key: 'goblet-squat',
    name: 'Sentadilla goblet',
    tagline: 'Fuerza de piernas base',
    anim: 'goblet-squat',
    equipment: ['mancuernas', 'mochila'],
    targets: ['Cuádriceps', 'Glúteo'],
    why: 'La fuerza general de piernas es el colchón que absorbe todo lo demás. Con el peso al pecho la técnica sale sola y la espalda no sufre.',
    setup: ['Mancuerna o mochila sujeta contra el pecho', 'Pies algo más anchos que la cadera'],
    execution: ['Baja con el pecho alto todo lo que te permita el tobillo', 'Rodillas en línea con los pies', 'Sube empujando el suelo'],
    mistakes: ['Levantar los talones', 'Dejar caer el pecho'],
    levels: [
      { n: 1, name: 'Una mancuerna de 5 kg' },
      { n: 2, name: 'Dos mancuernas' },
      { n: 3, name: 'Mochila cargada' },
    ],
    unilateral: false,
  },
  {
    key: 'split-squat',
    name: 'Zancada estática',
    tagline: 'Una pierna cada vez, como en la pista',
    anim: 'split-squat',
    equipment: ['mancuernas'],
    targets: ['Cuádriceps', 'Glúteo', 'Psoas'],
    why: 'En pickleball casi nunca apoyas las dos piernas a la vez. La zancada entrena esa realidad y corrige diferencias entre lados.',
    setup: ['Un pie delante y otro detrás, separados', 'Mancuernas colgando'],
    execution: ['Baja recto hasta casi tocar el suelo con la rodilla de atrás', 'Tronco vertical', 'Sube empujando con el pie de delante'],
    mistakes: ['Dar un paso adelante al subir', 'Inclinar mucho el tronco'],
    levels: [
      { n: 1, name: 'Sin peso' },
      { n: 2, name: 'Con mancuernas' },
      { n: 3, name: 'Con el pie de atrás elevado' },
    ],
    unilateral: true,
  },
  {
    key: 'step-up',
    name: 'Subida al escalón',
    tagline: 'Fuerza útil, con el escalón que ya tienes',
    anim: 'step-up',
    equipment: ['escalon', 'mancuernas'],
    targets: ['Cuádriceps', 'Glúteo'],
    why: 'Muy amable con el Aquiles porque no hay impacto, y muy exigente para el glúteo. Ideal para los días en que el tendón esté algo sensible pero quieras entrenar fuerte.',
    setup: ['Escalón de unos 30-40 cm', 'Pie entero sobre el escalón'],
    execution: ['Sube empujando con el talón de arriba', 'No te impulses con el pie de abajo', 'Baja en 3 s'],
    mistakes: ['Dar un saltito con la pierna de abajo', 'Bajar dejándose caer'],
    levels: [
      { n: 1, name: 'Escalón bajo, sin peso' },
      { n: 2, name: 'Escalón alto con mancuernas' },
      { n: 3, name: 'Escalón alto con mochila' },
    ],
    unilateral: true,
  },
  {
    key: 'wall-sit',
    name: 'Sentadilla isométrica en pared',
    tagline: 'Resistencia del cuádriceps sin impacto',
    anim: 'wall-sit',
    equipment: ['pared'],
    targets: ['Cuádriceps'],
    why: 'Cuando el cuádriceps se cansa dejas de amortiguar y todo el trabajo se va al tendón. Esto alarga tu aguante en los últimos puntos.',
    setup: ['Espalda pegada a la pared, muslos paralelos al suelo'],
    execution: ['Aguanta con las rodillas sobre los tobillos', 'Respira normal', 'Sal antes de perder la postura'],
    mistakes: ['Apoyar las manos en los muslos', 'Rodillas por delante de las puntas'],
    levels: [
      { n: 1, name: 'Rodillas a 90°, sin peso' },
      { n: 2, name: 'Aguante más largo' },
      { n: 3, name: 'Con mochila cargada' },
    ],
    unilateral: false,
  },

  /* ── Core ───────────────────────────────────────────────────────────── */
  {
    key: 'dead-bug',
    name: 'Dead bug',
    tagline: 'Core que protege la espalda al girar',
    anim: 'dead-bug',
    equipment: ['esterilla'],
    targets: ['Core'],
    why: 'Enseña al tronco a quedarse firme mientras brazos y piernas se mueven, que es lo que pasa en cada golpe. Sin eso, la fuerza se escapa y la carga baja a la cadera.',
    setup: ['Boca arriba, rodillas y brazos a 90°', 'Lumbar pegada al suelo'],
    execution: ['Estira brazo y pierna contrarios', 'Sin que la lumbar se despegue', 'Vuelve y cambia'],
    mistakes: ['Arquear la espalda', 'Ir rápido', 'Aguantar la respiración'],
    levels: [
      { n: 1, name: 'Solo las piernas' },
      { n: 2, name: 'Brazo y pierna contrarios' },
      { n: 3, name: 'Con pausa de 3 s' },
    ],
    unilateral: true,
  },
  {
    key: 'pallof-press',
    name: 'Pallof press con banda',
    tagline: 'Anti-rotación: el core del jugador de pala',
    anim: 'pallof-press',
    equipment: ['banda'],
    targets: ['Oblicuos', 'Core'],
    why: 'La banda intenta girarte y tú lo impides. Es la cualidad que transfiere la fuerza de las piernas a la pala sin que se pierda por el camino, y protege la zona lumbar.',
    setup: ['Banda anclada a un lado, a la altura del pecho', 'De pie, medio agachado, manos al pecho'],
    execution: ['Estira los brazos al frente', 'No dejes que el tronco gire ni un grado', 'Aguanta 2 s y vuelve'],
    mistakes: ['Girar los hombros', 'Poner el ancla demasiado floja'],
    levels: [
      { n: 1, name: 'Banda suave' },
      { n: 2, name: 'Banda media con pausa de 2 s' },
      { n: 3, name: 'Banda dura' },
    ],
    unilateral: true,
  },
  {
    key: 'side-plank',
    name: 'Plancha lateral',
    tagline: 'El lateral que sujeta la cadera',
    anim: 'side-plank',
    equipment: ['esterilla'],
    targets: ['Oblicuos', 'Glúteo medio'],
    why: 'Es la base sobre la que se construye la plancha con abducción. Además, aguantar bien la plancha lateral se relaciona con menos molestias de ingle.',
    setup: ['Antebrazo bajo el hombro', 'Cuerpo en línea'],
    execution: ['Sube la cadera y aguanta', 'Mirada al frente', 'Respira'],
    mistakes: ['Caer la cadera', 'Hombro hundido'],
    levels: [
      { n: 1, name: 'Rodillas apoyadas' },
      { n: 2, name: 'Piernas estiradas' },
      { n: 3, name: 'Piernas estiradas, aguante largo' },
    ],
    unilateral: true,
  },
  {
    key: 'bird-dog',
    name: 'Bird dog',
    tagline: 'Espalda y glúteo coordinados',
    anim: 'bird-dog',
    equipment: ['esterilla'],
    targets: ['Core', 'Glúteo'],
    why: 'Conecta glúteo y espalda en el mismo patrón, y es de los pocos ejercicios de core que además te enseña a extender la cadera sin arquear la lumbar.',
    setup: ['Cuadrupedia, manos bajo los hombros', 'Espalda neutra'],
    execution: ['Estira brazo y pierna contrarios', 'Aguanta 3 s sin girar la cadera', 'Vuelve despacio'],
    mistakes: ['Subir la pierna demasiado y arquear', 'Girar la pelvis'],
    levels: [
      { n: 1, name: 'Sin pausa' },
      { n: 2, name: 'Con pausa de 3 s' },
      { n: 3, name: 'Con pausa de 5 s' },
    ],
    unilateral: true,
  },

  /* ── Elasticidad y pista (fase 3) ───────────────────────────────────── */
  {
    key: 'pogo-hops',
    name: 'Pogos (saltos de tobillo)',
    tagline: 'Devuelve al tendón su capacidad de muelle',
    anim: 'pogo-hops',
    equipment: ['ninguno'],
    targets: ['Gemelo', 'Tendón de Aquiles'],
    why: 'Un tendón sano almacena y devuelve energía. La fuerza lenta no entrena eso; los pogos sí. Van en la fase 3, cuando el tendón ya tolera la carga pesada, nunca antes.',
    setup: ['De pie, manos en la cadera', 'Suelo firme, no césped blando'],
    execution: ['Bota desde el tobillo, rodillas casi rectas', 'Contactos muy cortos', 'Como un muelle, sin sentadillas entre saltos'],
    mistakes: ['Doblar mucho la rodilla', 'Contactos largos y blandos', 'Meterlos en fase 1 o 2'],
    painRule: 'Si al día siguiente la rigidez matutina sube, quítalos una semana.',
    levels: [
      { n: 1, name: 'Saltos pequeños' },
      { n: 2, name: 'Más altura, contacto muy corto' },
      { n: 3, name: 'A una pierna' },
    ],
    unilateral: false,
  },
  {
    key: 'lateral-bound',
    name: 'Salto lateral con aterrizaje',
    tagline: 'Aterrizar bien es no lesionarse',
    anim: 'lateral-bound',
    equipment: ['ninguno'],
    targets: ['Glúteo medio', 'Aductores'],
    why: 'El desplazamiento lateral explosivo es donde aparecen tus tirones. Practicarlo con aterrizaje congelado enseña al cuerpo a frenar bien.',
    setup: ['Espacio de 2-3 metros en el patio o la azotea'],
    execution: ['Salta lateralmente a una pierna', 'Aterriza y congela 1 s sin que la rodilla se meta', 'Salta al otro lado'],
    mistakes: ['Encadenar saltos sin congelar', 'Rodilla hacia dentro al caer'],
    levels: [
      { n: 1, name: 'Distancia corta, caes con las dos' },
      { n: 2, name: 'Aterrizaje a una pierna' },
      { n: 3, name: 'Más distancia' },
    ],
    unilateral: true,
  },
  {
    key: 'split-step',
    name: 'Split-step',
    tagline: 'El gesto que decide si llegas a la bola',
    anim: 'split-step',
    equipment: ['ninguno'],
    targets: ['Gemelo', 'Cuádriceps'],
    why: 'Es el pequeño salto que haces justo antes de que el rival golpee. Entrenarlo en seco mejora tu reacción y, sobre todo, enseña al tobillo a aterrizar amortiguando.',
    setup: ['De pie, peso en la parte delantera del pie', 'Pala en la mano si quieres'],
    execution: ['Salto corto, pies separándose ligeramente', 'Aterriza blando y en equilibrio', 'Sal inmediatamente hacia un lado'],
    mistakes: ['Saltar alto: es un salto mínimo', 'Aterrizar con las piernas rígidas'],
    levels: [
      { n: 1, name: 'Sin salida' },
      { n: 2, name: 'Con salida a un lado' },
      { n: 3, name: 'Salida a un lado aleatorio' },
    ],
    unilateral: false,
  },
  {
    key: 'skater-hold',
    name: 'Aterrizaje lateral con pausa',
    tagline: 'Frenar a una pierna, con control',
    anim: 'skater-hold',
    equipment: ['ninguno'],
    targets: ['Glúteo medio'],
    why: 'Congelar el aterrizaje dos segundos es lo que convierte un salto en un ejercicio de control. Es la versión segura del salto lateral para empezar.',
    setup: ['Espacio libre, suelo no resbaladizo'],
    execution: ['Salta lateralmente y cae sobre una pierna', 'Congela 2 s totalmente quieto', 'Cambia de lado'],
    mistakes: ['Apoyar el otro pie para no perder el equilibrio', 'Caer con la rodilla hacia dentro'],
    levels: [
      { n: 1, name: 'Distancia corta' },
      { n: 2, name: 'Distancia media' },
      { n: 3, name: 'Con la mirada en un punto fijo lejano' },
    ],
    unilateral: true,
  },

  /* ── Hombro (mantenimiento) ─────────────────────────────────────────── */
  {
    key: 'band-external-rotation',
    name: 'Rotación externa con banda',
    tagline: 'Mantenimiento del hombro de la pala',
    anim: 'band-external-rotation',
    equipment: ['banda'],
    targets: ['Manguito rotador', 'Hombro'],
    why: 'Tu hombro derecho tiene historia y jugar con pala carga siempre en la misma dirección. Dos minutos a la semana de rotación externa compensan ese desequilibrio.',
    setup: ['Banda anclada a la altura del codo', 'Codo pegado al costado, doblado 90°'],
    execution: ['Abre el antebrazo hacia fuera sin separar el codo', 'Aguanta 1 s', 'Vuelve despacio'],
    mistakes: ['Separar el codo del cuerpo', 'Usar una banda demasiado dura'],
    painRule: 'Si el hombro se queja, baja la tensión de la banda antes que quitar el ejercicio.',
    levels: [
      { n: 1, name: 'Banda suave' },
      { n: 2, name: 'Banda media' },
      { n: 3, name: 'Banda media con pausa de 2 s' },
    ],
    unilateral: true,
  },
  {
    key: 'band-pull-apart',
    name: 'Pull-apart con banda',
    tagline: 'Compensa las horas con el brazo por delante',
    anim: 'band-pull-apart',
    equipment: ['banda'],
    targets: ['Escápulas', 'Hombro posterior'],
    why: 'Equilibra la parte de atrás del hombro, que es la que sujeta la articulación cuando golpeas. Complementa lo que ya haces por las mañanas.',
    setup: ['Banda sujeta con las dos manos, brazos al frente'],
    execution: ['Abre los brazos juntando las escápulas', 'Aguanta 1 s', 'Vuelve controlando'],
    mistakes: ['Encoger los hombros hacia las orejas', 'Arquear la espalda'],
    levels: [
      { n: 1, name: 'Banda suave' },
      { n: 2, name: 'Banda media' },
      { n: 3, name: 'Banda media con pausa de 2 s' },
    ],
    unilateral: false,
  },
  {
    key: 'wall-slide',
    name: 'Deslizamiento en la pared',
    tagline: 'Movilidad de hombro sin forzar',
    anim: 'wall-slide',
    equipment: ['pared'],
    targets: ['Escápulas', 'Hombro'],
    why: 'Recupera el movimiento de subir el brazo con la escápula bien colocada, que es justo lo que se pierde tras un problema de hombro.',
    setup: ['Espalda, codos y muñecas contra la pared'],
    execution: ['Sube los brazos deslizando sin despegar nada', 'Sube solo hasta donde puedas mantener el contacto', 'Baja despacio'],
    mistakes: ['Arquear la lumbar para subir más', 'Despegar los codos'],
    levels: [
      { n: 1, name: 'Recorrido corto' },
      { n: 2, name: 'Recorrido completo' },
      { n: 3, name: 'Con pausa de 3 s arriba' },
    ],
    unilateral: false,
  },

  /* ── Calentamiento, movilidad y vuelta a la calma ───────────────────── */
  {
    key: 'march-jog',
    name: 'Trote suave en el sitio',
    tagline: 'Sube la temperatura antes de nada',
    anim: 'march-jog',
    equipment: ['ninguno'],
    targets: ['General'],
    why: 'Un tendón caliente es bastante más elástico que uno frío. Un par de minutos de trote suave cambian por completo cómo responde el Aquiles en los primeros puntos.',
    setup: ['Espacio mínimo, en el sitio'],
    execution: ['Trota suave levantando poco las rodillas', 'Brazos sueltos', 'Sube el ritmo poco a poco'],
    mistakes: ['Saltar fuerte desde el principio'],
    levels: [
      { n: 1, name: 'Suave' },
      { n: 2, name: 'Ritmo medio' },
      { n: 3, name: 'Con aceleraciones' },
    ],
    unilateral: false,
  },
  {
    key: 'leg-swings',
    name: 'Balanceos de pierna',
    tagline: 'Movilidad activa, no estiramiento',
    anim: 'leg-swings',
    equipment: ['pared'],
    targets: ['Cadera', 'Isquiotibiales'],
    why: 'Sustituye a los estiramientos estáticos que hacías antes de jugar. El balanceo prepara sin bajar la rigidez del tendón, que es justo lo que necesitas para rendir.',
    setup: ['Una mano en la pared', 'Pierna suelta'],
    execution: ['Balancea la pierna adelante y atrás sin forzar', 'Aumenta el recorrido poco a poco', 'Luego lateral'],
    mistakes: ['Forzar el rango a base de impulso', 'Arquear la espalda'],
    levels: [
      { n: 1, name: 'Recorrido corto' },
      { n: 2, name: 'Recorrido amplio' },
      { n: 3, name: 'Adelante-atrás y también lateral' },
    ],
    unilateral: true,
  },
  {
    key: 'ankle-circles',
    name: 'Círculos de tobillo',
    tagline: 'Despierta el tobillo en 30 segundos',
    anim: 'ankle-circles',
    equipment: ['pared'],
    targets: ['Tobillo'],
    why: 'Lubrica la articulación y te da información de cómo está el tobillo hoy antes de cargarlo.',
    setup: ['Apóyate en la pared', 'Un pie en el aire'],
    execution: ['Círculos amplios en un sentido', 'Luego en el otro', 'Cambia de pie'],
    mistakes: ['Círculos diminutos'],
    levels: [
      { n: 1, name: 'Círculos pequeños' },
      { n: 2, name: 'Círculos amplios' },
      { n: 3, name: 'Círculos amplios y dibujar letras con el pie' },
    ],
    unilateral: true,
  },
  {
    key: 'shadow-strokes',
    name: 'Golpes en seco con la pala',
    tagline: 'Lo que ya haces en la azotea, con orden',
    anim: 'shadow-strokes',
    equipment: ['pala'],
    targets: ['Oblicuos', 'Hombro'],
    why: 'Repasar el gesto sin bola te deja pensar en empujar desde las piernas en vez de con el brazo. Menos hombro, más cadera: bueno para el hombro derecho y para tu juego.',
    setup: ['Espacio libre en la azotea', 'Pala en la mano'],
    execution: ['Prepara con las rodillas blandas', 'Golpea empujando desde las piernas y girando el tronco', 'Alterna derecha y revés'],
    mistakes: ['Golpear solo con el brazo', 'Quedarse con las piernas rígidas'],
    levels: [
      { n: 1, name: 'Solo derecha' },
      { n: 2, name: 'Derecha y revés' },
      { n: 3, name: 'Con split-step antes de cada golpe' },
    ],
    unilateral: false,
  },
  {
    key: 'calf-stretch-wall',
    name: 'Estiramiento de gemelo y sóleo',
    tagline: 'Después de jugar, nunca antes',
    anim: 'calf-stretch-wall',
    equipment: ['pared'],
    targets: ['Gemelo', 'Sóleo'],
    why: 'Estirar el Aquiles en frío antes de jugar le quita rigidez justo cuando la necesitas, y es probable que sea parte del problema. Después del partido, en caliente y suave, sí tiene sentido.',
    setup: ['Manos en la pared, una pierna atrás'],
    execution: [
      'Pierna de atrás estirada, talón en el suelo: 30 s',
      'Luego dobla esa rodilla y aguanta otros 30 s (ese es el sóleo)',
      'Cambia de pierna',
    ],
    mistakes: ['Hacerlo antes de jugar', 'Levantar el talón', 'Tirar hasta el dolor'],
    painRule: 'Tirantez cómoda. Si notas pinchazo en el tendón, sal del estiramiento.',
    levels: [
      { n: 1, name: 'Aguante corto' },
      { n: 2, name: 'Aguante medio' },
      { n: 3, name: 'Aguante largo' },
    ],
    unilateral: true,
  },
  {
    key: 'hip-flexor-lunge',
    name: 'Estiramiento de flexor de cadera',
    tagline: 'Abre la cadera que el juego cierra',
    anim: 'hip-flexor-lunge',
    equipment: ['esterilla'],
    targets: ['Psoas', 'Glúteo'],
    why: 'Estar medio agachado todo el partido acorta el flexor de la cadera, y eso apaga el glúteo y carga el piramidal. Este estiramiento cierra el círculo.',
    setup: ['Zancada con la rodilla de atrás en el suelo'],
    execution: ['Mete el glúteo por debajo (retroversión)', 'Empuja la cadera hacia delante', 'Aguanta 30-40 s'],
    mistakes: ['Arquear la lumbar en vez de meter el glúteo', 'Adelantar solo la rodilla'],
    levels: [
      { n: 1, name: 'Sin brazo arriba' },
      { n: 2, name: 'Con el brazo de ese lado arriba' },
      { n: 3, name: 'Brazo arriba e inclinación al lado contrario' },
    ],
    unilateral: true,
  },
  {
    key: 'breathing-360',
    name: 'Respiración diafragmática',
    tagline: 'Baja pulsaciones y cierra la sesión',
    anim: 'breathing-360',
    equipment: ['esterilla'],
    targets: ['Diafragma', 'Core'],
    why: 'Espirar más largo que inspirar baja las pulsaciones rápido y ayuda a que el cuerpo entre en modo recuperación. Es el interruptor entre el partido y el resto del día.',
    setup: ['Boca arriba, rodillas dobladas', 'Manos en las costillas'],
    execution: ['Inspira 4 s por la nariz hinchando las costillas, no la barriga', 'Espira 6 s largo por la boca', 'Repite sin prisa'],
    mistakes: ['Subir los hombros al inspirar', 'Inspirar más rápido de lo que espiras'],
    levels: [
      { n: 1, name: 'Inspira 4 s, espira 6 s' },
      { n: 2, name: 'Inspira 4 s, retén 4 s, espira 8 s' },
      { n: 3, name: 'Igual, con más repeticiones' },
    ],
    unilateral: false,
  },
];

export const EXERCISES: Record<string, Exercise> = Object.fromEntries(
  list.map((e) => [e.key, e]),
);

export const EXERCISE_LIST = list;

export function getExercise(key: string): Exercise | undefined {
  return EXERCISES[key];
}

/** Display groups for the catalogue screen, in the order they appear there. */
export const EXERCISE_GROUPS: { name: string; blurb: string; keys: string[] }[] = [
  {
    name: 'Tobillo y Aquiles',
    blurb: 'El bloque principal: lo que hace que el tendón aguante.',
    keys: [
      'iso-calf-double', 'iso-calf-single', 'calf-raise-floor', 'calf-raise-single',
      'heel-drop-step', 'soleus-seated', 'soleus-wall-iso', 'knee-to-wall', 'toe-walk',
    ],
  },
  {
    name: 'Aductores e ingle',
    blurb: 'Para que dejen de darte tirones en los desplazamientos laterales.',
    keys: [
      'adductor-squeeze', 'copenhagen-short', 'copenhagen-long',
      'side-lying-adduction', 'lateral-lunge', 'cossack-squat',
    ],
  },
  {
    name: 'Cadera, glúteo y piramidal',
    blurb: 'Reparte el trabajo que ahora hace el piramidal él solo.',
    keys: [
      'glute-bridge', 'single-leg-bridge', 'clamshell-band', 'side-plank-abduction',
      'banded-lateral-walk', 'hip-airplane', 'hip-90-90', 'figure-4-stretch', 'single-leg-rdl',
    ],
  },
  {
    name: 'Pierna',
    blurb: 'Fuerza general: el colchón que absorbe todo lo demás.',
    keys: ['goblet-squat', 'split-squat', 'step-up', 'wall-sit'],
  },
  {
    name: 'Core',
    blurb: 'Transfiere la fuerza de las piernas a la pala.',
    keys: ['dead-bug', 'pallof-press', 'side-plank', 'bird-dog'],
  },
  {
    name: 'Elasticidad y pista',
    blurb: 'Solo en la fase 3, cuando el tendón ya tolera la carga pesada.',
    keys: ['pogo-hops', 'lateral-bound', 'split-step', 'skater-hold'],
  },
  {
    name: 'Hombro',
    blurb: 'Mantenimiento para el hombro de la pala.',
    keys: ['band-external-rotation', 'band-pull-apart', 'wall-slide'],
  },
  {
    name: 'Calentamiento y vuelta a la calma',
    blurb: 'Antes de jugar, movilidad activa. Después, estiramiento suave.',
    keys: [
      'march-jog', 'leg-swings', 'ankle-circles', 'shadow-strokes',
      'calf-stretch-wall', 'hip-flexor-lunge', 'breathing-360',
    ],
  },
];

/**
 * The catalogue flattened in the order the index page shows it, so stepping
 * through exercises one at a time follows the same path the eye just took.
 */
export const EXERCISE_ORDER: string[] = EXERCISE_GROUPS.flatMap((g) =>
  g.keys.filter((k) => EXERCISES[k]),
);

export interface ExerciseNeighbours {
  /** 1-based position in the whole catalogue. */
  index: number;
  total: number;
  groupName: string;
  prev: { key: string; name: string } | null;
  next: { key: string; name: string } | null;
}

/** Where an exercise sits in the catalogue, and what comes either side of it. */
export function exerciseNeighbours(key: string): ExerciseNeighbours | null {
  const i = EXERCISE_ORDER.indexOf(key);
  if (i === -1) return null;
  const at = (n: number) => {
    const k = EXERCISE_ORDER[n];
    return k ? { key: k, name: EXERCISES[k].name } : null;
  };
  return {
    index: i + 1,
    total: EXERCISE_ORDER.length,
    groupName: EXERCISE_GROUPS.find((g) => g.keys.includes(key))?.name ?? '',
    prev: at(i - 1),
    next: at(i + 1),
  };
}
