/* Generated by tools/figure3d/build.py. Do not edit. */
export interface Figure3DEntry {
  frames: string[];
  orient: string;
  camera: string;
  labels: string[];
  msPerFrame: number;
  steps: number;
  key: string;
}

export const FIGURE3D: Record<string, Figure3DEntry> = {
  "iso-calf-double": {
    "key": "iso-calf-double",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp",
      "f10.webp",
      "f11.webp",
      "f12.webp",
      "f13.webp",
      "f14.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Aguanta arriba",
      "Baja despacio",
      "Sube a puntillas"
    ],
    "msPerFrame": 280,
    "steps": 5
  },
  "iso-calf-single": {
    "key": "iso-calf-single",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp",
      "f10.webp",
      "f11.webp",
      "f12.webp",
      "f13.webp",
      "f14.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Aguanta arriba",
      "Baja despacio",
      "Sobre una pierna, sube"
    ],
    "msPerFrame": 280,
    "steps": 5
  },
  "calf-raise-floor": {
    "key": "calf-raise-floor",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp",
      "f10.webp",
      "f11.webp",
      "f12.webp",
      "f13.webp",
      "f14.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Aprieta arriba",
      "Baja en 3 s",
      "Sube en 2 s"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "calf-raise-single": {
    "key": "calf-raise-single",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp",
      "f10.webp",
      "f11.webp",
      "f12.webp",
      "f13.webp",
      "f14.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Aprieta arriba",
      "Baja en 3 s",
      "Sube sobre una pierna"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "heel-drop-step": {
    "key": "heel-drop-step",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Baja el talón por debajo",
      "En el escalón, arriba"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "soleus-seated": {
    "key": "soleus-seated",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "sentado",
    "camera": "lateral",
    "labels": [
      "Baja despacio",
      "Talones arriba"
    ],
    "msPerFrame": 280,
    "steps": 5
  },
  "soleus-wall-iso": {
    "key": "soleus-wall-iso",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Aguanta el sóleo",
      "Rodilla doblada contra la pared"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "knee-to-wall": {
    "key": "knee-to-wall",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Lleva la rodilla a tocar",
      "Rodilla lejos de la pared"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "toe-walk": {
    "key": "toe-walk",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Sin bajar los talones",
      "De puntillas, paso corto"
    ],
    "msPerFrame": 180,
    "steps": 5
  },
  "adductor-squeeze": {
    "key": "adductor-squeeze",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "boca-arriba",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Aprieta el cojín al 80 %",
      "Boca arriba, rodillas dobladas"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "copenhagen-short": {
    "key": "copenhagen-short",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-lado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Sube la cadera a la línea",
      "De lado, rodilla en la silla"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "copenhagen-long": {
    "key": "copenhagen-long",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-lado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Sube la cadera, cuerpo recto",
      "De lado, pie en la silla"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "side-lying-adduction": {
    "key": "side-lying-adduction",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-lado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Sube la pierna de abajo",
      "Tumbado de lado"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "lateral-lunge": {
    "key": "lateral-lunge",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Paso largo al lado",
      "De pie, pies juntos"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "cossack-squat": {
    "key": "cossack-squat",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Baja sobre una pierna",
      "Pies muy abiertos"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "glute-bridge": {
    "key": "glute-bridge",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "boca-arriba",
    "camera": "tres-cuartos",
    "labels": [
      "Sube la cadera",
      "Boca arriba, cadera abajo"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "single-leg-bridge": {
    "key": "single-leg-bridge",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "boca-arriba",
    "camera": "tres-cuartos",
    "labels": [
      "Sube la cadera",
      "Una pierna en el suelo"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "clamshell-band": {
    "key": "clamshell-band",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-lado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Abre la rodilla de arriba",
      "De lado, rodillas dobladas"
    ],
    "msPerFrame": 280,
    "steps": 5
  },
  "side-plank-abduction": {
    "key": "side-plank-abduction",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-lado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Sube la pierna de arriba",
      "Plancha lateral sobre el codo"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "banded-lateral-walk": {
    "key": "banded-lateral-walk",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Paso lateral sin juntar",
      "Semiflexión, banda tensa"
    ],
    "msPerFrame": 240,
    "steps": 5
  },
  "hip-airplane": {
    "key": "hip-airplane",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp",
      "f10.webp",
      "f11.webp",
      "f12.webp",
      "f13.webp",
      "f14.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Abre la cadera despacio",
      "Cierra con control",
      "De pie sobre una pierna, bisagra"
    ],
    "msPerFrame": 380,
    "steps": 5
  },
  "hip-90-90": {
    "key": "hip-90-90",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "sentado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Gira las dos rodillas al otro lado",
      "Sentado, 90 y 90"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "figure-4-stretch": {
    "key": "figure-4-stretch",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "boca-arriba",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Acerca la rodilla al pecho",
      "Boca arriba, tobillo sobre la rodilla"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "single-leg-rdl": {
    "key": "single-leg-rdl",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp",
      "f10.webp",
      "f11.webp",
      "f12.webp",
      "f13.webp",
      "f14.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "La cadera va hacia atrás",
      "Espalda y pierna en línea",
      "De pie sobre una pierna"
    ],
    "msPerFrame": 340,
    "steps": 5
  },
  "goblet-squat": {
    "key": "goblet-squat",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Baja en 3 s",
      "De pie con el peso al pecho"
    ],
    "msPerFrame": 340,
    "steps": 5
  },
  "split-squat": {
    "key": "split-squat",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Baja la rodilla de atrás",
      "Zancada, un pie delante"
    ],
    "msPerFrame": 340,
    "steps": 5
  },
  "step-up": {
    "key": "step-up",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Sube sin impulso",
      "Un pie en el escalón"
    ],
    "msPerFrame": 340,
    "steps": 5
  },
  "wall-sit": {
    "key": "wall-sit",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Aguanta 90 grados",
      "Espalda en la pared"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "dead-bug": {
    "key": "dead-bug",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "boca-arriba",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Estira brazo y pierna contrarios",
      "Boca arriba, brazos al techo"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "pallof-press": {
    "key": "pallof-press",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Estira los brazos al frente",
      "Banda al pecho, no te gires"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "side-plank": {
    "key": "side-plank",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-lado",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Sube la cadera hasta la línea",
      "Apóyate en el codo"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "bird-dog": {
    "key": "bird-dog",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "cuadrupedia",
    "camera": "tres-cuartos",
    "labels": [
      "Estira brazo y pierna contrarios",
      "A cuatro patas"
    ],
    "msPerFrame": 340,
    "steps": 5
  },
  "pogo-hops": {
    "key": "pogo-hops",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Rebota desde el tobillo",
      "Contacto corto y rígido"
    ],
    "msPerFrame": 84,
    "steps": 5
  },
  "lateral-bound": {
    "key": "lateral-bound",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Congela 1 s el aterrizaje",
      "Salta al lado"
    ],
    "msPerFrame": 220,
    "steps": 5
  },
  "split-step": {
    "key": "split-step",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Cae listo para salir",
      "Pequeño salto"
    ],
    "msPerFrame": 124,
    "steps": 5
  },
  "skater-hold": {
    "key": "skater-hold",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Aguanta sin que la rodilla caiga",
      "Cae sobre una pierna"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "band-external-rotation": {
    "key": "band-external-rotation",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Abre el antebrazo",
      "Codo pegado al cuerpo"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "band-pull-apart": {
    "key": "band-pull-apart",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Abre hasta el pecho",
      "Brazos al frente"
    ],
    "msPerFrame": 300,
    "steps": 5
  },
  "wall-slide": {
    "key": "wall-slide",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "frontal",
    "labels": [
      "Desliza hacia arriba",
      "Brazos en la pared, codos abajo"
    ],
    "msPerFrame": 320,
    "steps": 5
  },
  "march-jog": {
    "key": "march-jog",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Casi andando",
      "Trote muy suave"
    ],
    "msPerFrame": 140,
    "steps": 5
  },
  "leg-swings": {
    "key": "leg-swings",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Pierna atrás, relajada",
      "Pierna adelante"
    ],
    "msPerFrame": 200,
    "steps": 5
  },
  "ankle-circles": {
    "key": "ankle-circles",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "En los dos sentidos",
      "Dibuja círculos con el tobillo"
    ],
    "msPerFrame": 200,
    "steps": 5
  },
  "shadow-strokes": {
    "key": "shadow-strokes",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Acompaña con el cuerpo",
      "Prepara el golpe"
    ],
    "msPerFrame": 200,
    "steps": 5
  },
  "calf-stretch-wall": {
    "key": "calf-stretch-wall",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "lateral",
    "labels": [
      "Ahora dobla la de atrás, sóleo",
      "Pierna atrás estirada"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "hip-flexor-lunge": {
    "key": "hip-flexor-lunge",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "de-pie",
    "camera": "tres-cuartos",
    "labels": [
      "Mete la cadera hacia delante",
      "Rodilla en el suelo"
    ],
    "msPerFrame": 360,
    "steps": 5
  },
  "breathing-360": {
    "key": "breathing-360",
    "frames": [
      "f00.webp",
      "f01.webp",
      "f02.webp",
      "f03.webp",
      "f04.webp",
      "f05.webp",
      "f06.webp",
      "f07.webp",
      "f08.webp",
      "f09.webp"
    ],
    "orient": "boca-arriba",
    "camera": "tres-cuartos-alto",
    "labels": [
      "Inspira abriendo las costillas",
      "Boca arriba, manos en las costillas"
    ],
    "msPerFrame": 520,
    "steps": 5
  }
};
