"""
Render one or every exercise. Run under Blender:

    blender -b -noaudio -P tools/figure3d/build.py -- --only hip-airplane
    blender -b -noaudio -P tools/figure3d/build.py -- --all --size 320
"""

import json
import os
import sys
import time

import bpy

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)

import rig      # noqa: E402
import scene    # noqa: E402
import poses    # noqa: E402

OUT = os.path.join(ROOT, 'public', 'fig3d')


def argv():
    a = sys.argv
    return a[a.index('--') + 1:] if '--' in a else []


def lerp(a, b, t):
    out = {}
    for k in set(a) | set(b):
        va, vb = a.get(k, 0.0), b.get(k, 0.0)
        out[k] = va + (vb - va) * t
    return out


def ease(t):
    return t * t * (3.0 - 2.0 * t)


def render_exercise(key, spec, size, steps):
    mats = scene.setup(size, spec.get('camera', 'tres-cuartos'))
    meshes = scene.unit_meshes()
    props = []
    for p in spec.get('props', []):
        props += scene.build_prop(p, mats, spec)

    frames = spec['frames']
    out_dir = os.path.join(OUT, key)
    os.makedirs(out_dir, exist_ok=True)

    n = len(frames)
    made = []
    index = 0
    for i in range(n):
        a, b = frames[i]['p'], frames[(i + 1) % n]['p']
        for s in range(steps):
            t = ease(s / float(steps))
            joints = rig.solve(lerp(a, b, t), spec.get('orient', 'de-pie'))
            objs = scene.build_figure(joints, mats, meshes, spec.get('highlight'))
            bpy.context.scene.render.filepath = os.path.join(out_dir, f'f{index:02d}.webp')
            bpy.ops.render.render(write_still=True)
            for o in objs:
                bpy.data.objects.remove(o, do_unlink=True)
            made.append(f'f{index:02d}.webp')
            index += 1
    return {
        'key': key,
        'frames': made,
        'orient': spec.get('orient', 'de-pie'),
        'camera': spec.get('camera', 'tres-cuartos'),
        'labels': [f.get('label', '') for f in frames],
        'msPerFrame': spec.get('ms', 1400) // steps,
        'steps': steps,
    }


def main():
    args = argv()
    size = 320
    steps = 6
    only = None
    if '--size' in args:
        size = int(args[args.index('--size') + 1])
    if '--steps' in args:
        steps = int(args[args.index('--steps') + 1])
    if '--only' in args:
        only = args[args.index('--only') + 1]

    keys = [only] if only else list(poses.POSES.keys())
    manifest = {}
    t0 = time.time()
    for i, key in enumerate(keys, 1):
        spec = poses.POSES.get(key)
        if not spec:
            print(f'SKIP {key}: sin pose')
            continue
        scene.clear()
        manifest[key] = render_exercise(key, spec, size, steps)
        print(f'[{i}/{len(keys)}] {key} · {len(manifest[key]["frames"])} fotogramas '
              f'· {time.time() - t0:.0f}s', flush=True)

    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, 'manifest.json')
    if only and os.path.exists(path):
        prev = json.load(open(path))
        prev.update(manifest)
        manifest = prev
    with open(path, 'w') as fh:
        json.dump(manifest, fh, indent=1, ensure_ascii=False)

    # A typed copy for the app, so the player knows frame counts and captions
    # without fetching anything.
    ts = os.path.join(ROOT, 'src', 'lib', 'program', 'figure3d.ts')
    with open(ts, 'w') as fh:
        fh.write('/* Generated by tools/figure3d/build.py. Do not edit. */\n')
        fh.write('export interface Figure3DEntry {\n')
        fh.write('  frames: string[];\n  orient: string;\n  camera: string;\n')
        fh.write('  labels: string[];\n  msPerFrame: number;\n  steps: number;\n  key: string;\n}\n\n')
        fh.write('export const FIGURE3D: Record<string, Figure3DEntry> = ')
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write(';\n')
    print(f'LISTO {len(manifest)} ejercicios en {time.time() - t0:.0f}s')


main()
